# Generated by Django 4.2.2 on 2023-07-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_no', models.IntegerField()),
                ('Student_Fname', models.CharField(max_length=30)),
                ('Student_Lname', models.CharField(max_length=25)),
            ],
        ),
    ]
